/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.Controlador;
import Modelo.Departamento;
import java.text.SimpleDateFormat;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author David
 */
public class ListarDepartamentos extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListarDepartamentos
     */
    
    private final Controlador controlador;
    
    public ListarDepartamentos(Controlador controlador) {
        initComponents();
        this.controlador = controlador;
        cargarDepartamentosEnTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloVentana = new javax.swing.JLabel();
        botonRefrescar = new javax.swing.JButton();
        contenedorTabla = new javax.swing.JScrollPane();
        tablaContenido = new javax.swing.JTable();

        setClosable(true);
        setTitle("Listado de Departamentos");

        tituloVentana.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        tituloVentana.setText("Listado de Departamentos");
        tituloVentana.setToolTipText("");

        botonRefrescar.setText("Refrescar Tabla");
        botonRefrescar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRefrescarActionPerformed(evt);
            }
        });

        tablaContenido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "# Articulos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaContenido.getTableHeader().setReorderingAllowed(false);
        contenedorTabla.setViewportView(tablaContenido);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contenedorTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tituloVentana)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonRefrescar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloVentana)
                    .addComponent(botonRefrescar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedorTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 295, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Carga y muestra todos los registros.
    */
    private void cargarDepartamentosEnTabla() {
        try {
            mostrarRegistrosEnTabla();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error al listar registros: " + e.getMessage(),
                "Error de Listado",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * Muestra el listado de departamentos de forma tabular.
     * Si no hay registros, muestra un mensaje de “No hay registros”.
     *
    */
    private void mostrarRegistrosEnTabla() {
        // Referencia: https://stackoverflow.com/questions/2732865/how-to-update-jtable
        DefaultTableModel modelo = (DefaultTableModel) tablaContenido.getModel();
        modelo.setRowCount(0); // Limpiar tabla
              
        boolean hayRegistros = false;
        
        // Obtener departamentos actuales
        Departamento[] departamentos = controlador.obtenerDepartamentosActuales();
        
        // Recorrer iterador mientras hayan registros
        // Referencia de metodos: https://docs.oracle.com/javase/8/docs/api/java/util/Iterator.html
        // Recorrer array de departamentos
        for (Departamento departamento : departamentos) {
            hayRegistros = true;

            // Llenar filas
            Object[] fila = new Object[] {
                departamento.getId(),
                departamento.getNombre(),
                departamento.getContadorArticulos()
            };
            modelo.addRow(fila);
        }
        // Desplegar fila en caso de no tener registros
        if (!hayRegistros) {
            modelo.addRow(new Object[] { "No hay departamentos registrados", "", "" });
        }
    }
    
    private void botonRefrescarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRefrescarActionPerformed
        cargarDepartamentosEnTabla();
    }//GEN-LAST:event_botonRefrescarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonRefrescar;
    private javax.swing.JScrollPane contenedorTabla;
    private javax.swing.JTable tablaContenido;
    private javax.swing.JLabel tituloVentana;
    // End of variables declaration//GEN-END:variables
}
