package Vista;

import javax.swing.JOptionPane;
import Modelo.Departamento;

/*
 * Universidad Estatal a Distancia (UNED)
 * Cuatrimestre: I Cuatrimestre 2026
 * Proyecto: Proyecto 2 - Estructura de Datos
 * Descripción: Pantalla para registrar nuevos departamentos en el sistema
 * Estudiante: Jose David Canizales Azocar
 * Fecha: Marzo 2026
 */
import Controlador.Controlador;
import javax.swing.table.DefaultTableModel;
public class RegistroDepartamento extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistroDepartamento
    */
    
    private final Controlador controlador;
    
    public RegistroDepartamento(Controlador controlador) {
        initComponents();
        this.controlador = controlador;
        cargarDepartamentosEnTabla();
        this.id.setText(
            String.valueOf(controlador.getContadorDepartamentos() + 1)
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloVentana = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JButton();
        botonRegistrar = new javax.swing.JButton();
        contenedorTabla = new javax.swing.JScrollPane();
        tablaContenido = new javax.swing.JTable();

        setClosable(true);
        setTitle("Registro de Departamento");

        tituloVentana.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        tituloVentana.setText("Registro de Departamento");
        tituloVentana.setToolTipText("");

        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        lblId.setText("ID");

        id.setEditable(false);
        id.setFocusable(false);
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        lblNombre.setText("Nombre");

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonRegistrar.setText("Registrar");
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });

        tablaContenido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "# Articulos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaContenido.getTableHeader().setReorderingAllowed(false);
        contenedorTabla.setViewportView(tablaContenido);
        if (tablaContenido.getColumnModel().getColumnCount() > 0) {
            tablaContenido.getColumnModel().getColumn(0).setMinWidth(60);
            tablaContenido.getColumnModel().getColumn(0).setPreferredWidth(60);
            tablaContenido.getColumnModel().getColumn(0).setMaxWidth(60);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contenedorTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblId)
                                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombre)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNombre)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(tituloVentana)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(botonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(tituloVentana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(lblNombre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    // Limpia todos los campos del formulario dejandolos en su estado inicial.
    private void limpiarFormulario() {
        this.nombre.setText("");
        this.id.setText(
            String.valueOf(controlador.getContadorDepartamentos() + 1)
        );
    }
    
    /**
     * Carga y muestra todos los registros.
    */
    private void cargarDepartamentosEnTabla() {
        try {
            mostrarRegistrosEnTabla();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error al listar registros: " + e.getMessage(),
                "Error de Listado",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * Muestra el listado de departamentos de forma tabular.
     * Si no hay registros, muestra un mensaje de “No hay registros”.
     *
    */
    private void mostrarRegistrosEnTabla() {
        // Referencia: https://stackoverflow.com/questions/2732865/how-to-update-jtable
        DefaultTableModel modelo = (DefaultTableModel) tablaContenido.getModel();
        modelo.setRowCount(0); // Limpiar tabla
              
        boolean hayRegistros = false;
        
        // Obtener departamentos actuales
        Departamento[] departamentos = controlador.obtenerDepartamentosActuales();
        
        // Recorrer array de departamentos
        for (Departamento departamento : departamentos) {
            hayRegistros = true;

            // Llenar filas
            Object[] fila = new Object[] {
                departamento.getId(),
                departamento.getNombre(),
                departamento.getContadorArticulos()
            };
            modelo.addRow(fila);
        }
        // Desplegar fila en caso de no tener registros
        if (!hayRegistros) {
            modelo.addRow(new Object[] { 0, "No hay departamentos registrados", "" });
        }
    }
    
    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        int opcion = JOptionPane.showOptionDialog(
            this,
            "Desea abortar el registro?",
            "Confirmar",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            new Object[]{"Si", "No"},
            "No"
        );
        if (opcion == JOptionPane.YES_OPTION) {
            limpiarFormulario();
            this.dispose();
        }
    }//GEN-LAST:event_botonCancelarActionPerformed

    // Valida que los campos del formulario no esten vacios antes de registrar.
    private void validarCampos() {
        String nombre = this.nombre.getText().trim();
        if (nombre.isEmpty()) {
            throw new IllegalArgumentException("El campo nombre es obligatorio");
        }
    }
    
    /**
     * Captura los datos del formulario, valida su formato e intenta
     * registrar el departamento.
    */
    public void capturarDatosFormulario() {
        try {
            validarCampos();
            String nombre = this.nombre.getText().trim();
            controlador.agregarDepartamento(nombre);
            limpiarFormulario();
            cargarDepartamentosEnTabla();
        } catch (IllegalArgumentException e) {
            // Error de validación - mensaje específico
            JOptionPane.showMessageDialog(this, 
                e.getMessage(), 
                "Error de Validacion", 
                JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
             // Error inesperado
             JOptionPane.showMessageDialog(this, 
                 "Error inesperado: " + e.getMessage(), 
                 "Error", 
                 JOptionPane.ERROR_MESSAGE);
         }
    }
       
    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        capturarDatosFormulario();
    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JScrollPane contenedorTabla;
    private javax.swing.JTextField id;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField nombre;
    private javax.swing.JTable tablaContenido;
    private javax.swing.JLabel tituloVentana;
    // End of variables declaration//GEN-END:variables
}
