package Vista;

/*
 * Universidad Estatal a Distancia (UNED)
 * Cuatrimestre: I Cuatrimestre 2026
 * Proyecto: Proyecto 2 - Estructura de Datos
 * Descripción: Pantalla para registrar nuevos articulos en el sistema
 * Estudiante: Jose David Canizales Azocar
 * Fecha: Marzo 2026
 */
import Controlador.Controlador;
import static Modelo.Articulo.CATEGORIAS;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import Modelo.Departamento;
import Modelo.Articulo;
public class RegistroArticulo extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistroArticulos
    */
    
    private final Controlador controlador;
    
    public RegistroArticulo(Controlador controlador) {
        initComponents();
        this.controlador = controlador;
        cargarDepartamentosEnTabla();
        this.idArticulo.setText(
            String.valueOf(controlador.getContadorArticulosGlobal() + 1)
        );
        // Cargar categorias en combobox
        cargarCategorias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tituloVentana = new javax.swing.JLabel();
        tituloTablaDepartamento = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        lblIdDepartamento = new javax.swing.JLabel();
        idDepartamento = new javax.swing.JTextField();
        lblCategoria = new javax.swing.JLabel();
        lblIdArticulo = new javax.swing.JLabel();
        idArticulo = new javax.swing.JTextField();
        categoria = new javax.swing.JComboBox<>();
        botonCancelar = new javax.swing.JButton();
        botonRegistrar = new javax.swing.JButton();
        contenedorTablaDepartamento = new javax.swing.JScrollPane();
        tablaDepartamento = new javax.swing.JTable();
        tituloTablaArticulo = new javax.swing.JLabel();
        contenedorTablaArticulo = new javax.swing.JScrollPane();
        tablaArticulo = new javax.swing.JTable();
        botonRefrescarDepartamentos = new javax.swing.JButton();

        setClosable(true);
        setTitle("Registro de Articulos");

        tituloVentana.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        tituloVentana.setText("Registro de Articulos");
        tituloVentana.setToolTipText("");

        tituloTablaDepartamento.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tituloTablaDepartamento.setText("Listado de Departamentos");
        tituloTablaDepartamento.setToolTipText("");

        lblNombre.setText("Nombre");

        nombre.setEnabled(false);
        nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreActionPerformed(evt);
            }
        });

        lblIdDepartamento.setText("ID Depto.");

        idDepartamento.setEditable(false);
        idDepartamento.setFocusable(false);
        idDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idDepartamentoActionPerformed(evt);
            }
        });

        lblCategoria.setText("Categoria");

        lblIdArticulo.setText("ID Articulo");

        idArticulo.setEditable(false);
        idArticulo.setFocusable(false);
        idArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idArticuloActionPerformed(evt);
            }
        });

        categoria.setEnabled(false);
        categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriaActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.setEnabled(false);
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonRegistrar.setText("Registrar");
        botonRegistrar.setEnabled(false);
        botonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistrarActionPerformed(evt);
            }
        });

        tablaDepartamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "# Articulos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaDepartamento.getTableHeader().setReorderingAllowed(false);
        tablaDepartamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaDepartamentoMouseClicked(evt);
            }
        });
        contenedorTablaDepartamento.setViewportView(tablaDepartamento);
        if (tablaDepartamento.getColumnModel().getColumnCount() > 0) {
            tablaDepartamento.getColumnModel().getColumn(0).setMinWidth(60);
            tablaDepartamento.getColumnModel().getColumn(0).setPreferredWidth(60);
            tablaDepartamento.getColumnModel().getColumn(0).setMaxWidth(60);
        }

        tituloTablaArticulo.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tituloTablaArticulo.setText("Listado de Articulos");
        tituloTablaArticulo.setToolTipText("");

        tablaArticulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Categoria"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaArticulo.getTableHeader().setReorderingAllowed(false);
        contenedorTablaArticulo.setViewportView(tablaArticulo);
        if (tablaArticulo.getColumnModel().getColumnCount() > 0) {
            tablaArticulo.getColumnModel().getColumn(0).setMinWidth(60);
            tablaArticulo.getColumnModel().getColumn(0).setPreferredWidth(60);
            tablaArticulo.getColumnModel().getColumn(0).setMaxWidth(60);
        }

        botonRefrescarDepartamentos.setText("Refrescar Tabla");
        botonRefrescarDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRefrescarDepartamentosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(contenedorTablaDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdDepartamento)
                            .addComponent(idDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblIdArticulo)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(idArticulo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCategoria)
                            .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(contenedorTablaArticulo, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tituloTablaArticulo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloTablaDepartamento)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(197, 197, 197)
                                .addComponent(tituloVentana)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonRefrescarDepartamentos)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tituloVentana)
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonRefrescarDepartamentos)
                            .addComponent(tituloTablaDepartamento))
                        .addGap(10, 10, 10)))
                .addComponent(contenedorTablaDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdDepartamento)
                            .addComponent(lblNombre)
                            .addComponent(lblCategoria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblIdArticulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tituloTablaArticulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedorTablaArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreActionPerformed

    // Limpia todos los campos del formulario dejandolos en su estado inicial.
    private void limpiarFormulario() {
        this.nombre.setText("");
        this.idArticulo.setText(
            String.valueOf(controlador.getContadorArticulosGlobal() + 1)
        );
        this.categoria.setSelectedIndex(0);
    }
    
    /**
     * Muestra el listado de departamentos de forma tabular.
     * Si no hay registros, muestra un mensaje de “No hay registros”.
     *
    */
    private void mostrarRegistrosEnTablaArticulo() {
        // Referencia: https://stackoverflow.com/questions/2732865/how-to-update-jtable
        DefaultTableModel modelo = (DefaultTableModel) tablaArticulo.getModel();
        modelo.setRowCount(0); // Limpiar tabla
                     
        // Obtener articulos del departamento seleccionado
        int idDepartamento = Integer.parseInt(
            this.idDepartamento.getText().trim()
        );
        
        Departamento departamento = controlador.buscarDepartamento(idDepartamento);
        Articulo[] articulos = departamento.getArticulos();
        int contador = departamento.getContadorArticulos();
        // Si no hay articulos, mostrar el mensaje en la tabla
        if (contador == 0) {
            modelo.addRow(new Object[] { "", "No hay articulos registrados", "" });
            return;
        }
        
        // Recorrer array de articulos
        for (int i = 0; i < contador; i++) {
            Articulo articulo = articulos[i];
            // Validar que no sea null
            if (articulo == null) {
                continue;
            }
            Object[] fila = new Object[] {
                articulo.getId(),
                articulo.getNombre(),
                articulo.getCategoria()
            };
            modelo.addRow(fila);
        }

    }
      
    /**
     * Carga y muestra todos los articulos de un departamento.
    */
    private void cargarArticulosEnTabla() {
        try {
            mostrarRegistrosEnTablaArticulo();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error al listar registros: " + e.getMessage(),
                "Error de Listado",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * Carga y muestra todos los registros.
    */
    private void cargarDepartamentosEnTabla() {
        try {
            mostrarRegistrosEnTablaDepartamento();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error al listar registros: " + e.getMessage(),
                "Error de Listado",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * Muestra el listado de departamentos de forma tabular.
     * Si no hay registros, muestra un mensaje de “No hay registros”.
     *
    */
    private void mostrarRegistrosEnTablaDepartamento() {
        // Referencia: https://stackoverflow.com/questions/2732865/how-to-update-jtable
        DefaultTableModel modelo = (DefaultTableModel) tablaDepartamento.getModel();
        modelo.setRowCount(0); // Limpiar tabla
              
        boolean hayRegistros = false;
        
        // Obtener departamentos actuales
        Departamento[] departamentos = controlador.obtenerDepartamentosActuales();
       
        // Recorrer array de departamentos
        for (Departamento departamento : departamentos) {
            hayRegistros = true;

            // Llenar filas
            Object[] fila = new Object[] {
                departamento.getId(),
                departamento.getNombre(),
                departamento.getContadorArticulos()
            };
            modelo.addRow(fila);
        }
        // Desplegar fila en caso de no tener registros
        if (!hayRegistros) {
            modelo.addRow(new Object[] { "", "No hay departamentos registrados", "" });
        }
    }
    
    // Cargar categorias en el combobox
    private void cargarCategorias() {
        categoria.setModel(
            new javax.swing.DefaultComboBoxModel<>(
            CATEGORIAS
        ));
    } 
    
    // Cancelar el registro
    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        limpiarFormulario();
        this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    // Valida que los campos del formulario no esten vacios antes de registrar.
    private void validarCampos() {
        String nombre = this.nombre.getText().trim();
        if (nombre.isEmpty()) {
            throw new IllegalArgumentException("El campo nombre es obligatorio");
        }
        String categoria = (String) this.categoria.getSelectedItem();
        if (categoria == null  ) {
            throw new IllegalArgumentException("Debe seleccionar una categoria");
        }
    }

    /**
    * Habilita los campos y botones del formulario
    * Se llama al seleccionar un registro de la tabla.
    */
    private void habilitarCampos() {
        this.nombre.setEnabled(true);
        this.categoria.setEnabled(true);
        this.botonRegistrar.setEnabled(true);
        this.botonCancelar.setEnabled(true);
    }
    
    /**
     * Captura los datos del formulario, valida su formato e intenta
     * registrar el articulo.
    */
    public void capturarDatosFormulario() {
        try {
            validarCampos();
            String nombre = this.nombre.getText().trim();
            int idDepartamento = Integer.parseInt(
                this.idDepartamento.getText().trim()
            );
            String categoria = (String) this.categoria.getSelectedItem();
            controlador.agregarArticulo(
                idDepartamento,
                nombre,
                categoria
            );
            limpiarFormulario();
            cargarArticulosEnTabla();
        } catch (IllegalArgumentException e) {
            // Error de validación - mensaje específico
            JOptionPane.showMessageDialog(this, 
                e.getMessage(), 
                "Error de Validacion", 
                JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
             // Error inesperado
             JOptionPane.showMessageDialog(this, 
                 "Error inesperado: " + e.getMessage(), 
                 "Error", 
                 JOptionPane.ERROR_MESSAGE);
         }
    }
    
    
       
    private void botonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistrarActionPerformed
        capturarDatosFormulario();
    }//GEN-LAST:event_botonRegistrarActionPerformed

    private void idDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idDepartamentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idDepartamentoActionPerformed

    private void categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoriaActionPerformed

    private void idArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idArticuloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idArticuloActionPerformed

    // Obtener informacion del departamento seleccionado
    private void tablaDepartamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDepartamentoMouseClicked
        // Referencia: https://stackoverflow.com/questions/29345792/java-jtable-getting-the-data-of-the-selected-row
        int fila = tablaDepartamento.getSelectedRow();
        if (fila >= 0) {
            // Obtener ID del departamento seleccionado
            int id = (int) tablaDepartamento.getValueAt(fila, 0);
            if (id > 0) {
                // Mostrar datos en los inputs
                this.idDepartamento.setText(String.valueOf(id));
                habilitarCampos();
                cargarArticulosEnTabla();
            }
        }
    }//GEN-LAST:event_tablaDepartamentoMouseClicked

    private void botonRefrescarDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRefrescarDepartamentosActionPerformed
        cargarDepartamentosEnTabla();
    }//GEN-LAST:event_botonRefrescarDepartamentosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonRefrescarDepartamentos;
    private javax.swing.JButton botonRegistrar;
    private javax.swing.JComboBox<String> categoria;
    private javax.swing.JScrollPane contenedorTablaArticulo;
    private javax.swing.JScrollPane contenedorTablaDepartamento;
    private javax.swing.JTextField idArticulo;
    private javax.swing.JTextField idDepartamento;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblIdArticulo;
    private javax.swing.JLabel lblIdDepartamento;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTextField nombre;
    private javax.swing.JTable tablaArticulo;
    private javax.swing.JTable tablaDepartamento;
    private javax.swing.JLabel tituloTablaArticulo;
    private javax.swing.JLabel tituloTablaDepartamento;
    private javax.swing.JLabel tituloVentana;
    // End of variables declaration//GEN-END:variables
}
