package Vista;

import Controlador.Controlador;
import Modelo.Departamento;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Universidad Estatal a Distancia (UNED)
 * Cuatrimestre: I Cuatrimestre 2026
 * Proyecto: Proyecto 2 - Estructura de Datos
 * Descripción: Pantalla para gestionar el traslado de articulos en el sistema
 * Estudiante: Jose David Canizales Azocar
 * Fecha: Marzo 2026
 */

public class TrasladoArticulos extends javax.swing.JInternalFrame {

    /**
     * Creates new form TrasladoArticulos
     */
    
    private final Controlador controlador;
    
    public TrasladoArticulos(Controlador controlador) {
        initComponents();
        this.controlador = controlador;
        cargarDepartamentosEnTabla();
        cargarComboboxes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorTabla = new javax.swing.JScrollPane();
        tablaContenido = new javax.swing.JTable();
        tituloVentana = new javax.swing.JLabel();
        lbOrigen = new javax.swing.JLabel();
        lblDestino = new javax.swing.JLabel();
        departamentoOrigen = new javax.swing.JComboBox<>();
        departamentoDestino = new javax.swing.JComboBox<>();
        botonCancelar = new javax.swing.JButton();
        botonTrasladar = new javax.swing.JButton();
        tituloTablaDepartamento = new javax.swing.JLabel();
        botonRefrescarDepartamentos = new javax.swing.JButton();

        setClosable(true);
        setTitle("Trasladar Articulos");

        tablaContenido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "# Articulos"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaContenido.getTableHeader().setReorderingAllowed(false);
        contenedorTabla.setViewportView(tablaContenido);
        if (tablaContenido.getColumnModel().getColumnCount() > 0) {
            tablaContenido.getColumnModel().getColumn(0).setMinWidth(60);
            tablaContenido.getColumnModel().getColumn(0).setPreferredWidth(60);
            tablaContenido.getColumnModel().getColumn(0).setMaxWidth(60);
        }

        tituloVentana.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        tituloVentana.setText("Trasladar Articulos");
        tituloVentana.setToolTipText("");

        lbOrigen.setText("Departamento de Origen");

        lblDestino.setText("Departamento de Destino");

        departamentoOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departamentoOrigenActionPerformed(evt);
            }
        });

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonTrasladar.setText("Trasladar");
        botonTrasladar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonTrasladarActionPerformed(evt);
            }
        });

        tituloTablaDepartamento.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        tituloTablaDepartamento.setText("Listado de Departamentos");
        tituloTablaDepartamento.setToolTipText("");

        botonRefrescarDepartamentos.setText("Refrescar Tabla");
        botonRefrescarDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRefrescarDepartamentosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(tituloVentana)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonTrasladar, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tituloTablaDepartamento)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(botonRefrescarDepartamentos))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbOrigen)
                                    .addComponent(departamentoOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblDestino)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(departamentoDestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(contenedorTabla, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(tituloVentana)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tituloTablaDepartamento, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonRefrescarDepartamentos, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedorTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbOrigen)
                    .addComponent(lblDestino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departamentoOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(departamentoDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonTrasladar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Carga y muestra todos los registros.
    */
    private void cargarDepartamentosEnTabla() {
        try {
            mostrarRegistrosEnTabla();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error al listar registros: " + e.getMessage(),
                "Error de Listado",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * Muestra el listado de departamentos de forma tabular.
     * Si no hay registros, muestra un mensaje de “No hay registros”.
     *
    */
    private void mostrarRegistrosEnTabla() {
        // Referencia: https://stackoverflow.com/questions/2732865/how-to-update-jtable
        DefaultTableModel modelo = (DefaultTableModel) tablaContenido.getModel();
        modelo.setRowCount(0); // Limpiar tabla
              
        boolean hayRegistros = false;
        
        // Obtener departamentos actuales
        Departamento[] departamentos = controlador.obtenerDepartamentosActuales();
        
        // Recorrer array de departamentos
        for (Departamento departamento : departamentos) {
            hayRegistros = true;

            // Llenar filas
            Object[] fila = new Object[] {
                departamento.getId(),
                departamento.getNombre(),
                departamento.getContadorArticulos()
            };
            modelo.addRow(fila);
        }
        // Desplegar fila en caso de no tener registros
        if (!hayRegistros) {
            modelo.addRow(new Object[] { 0, "No hay departamentos registrados", "" });
        }
    }
    
    // Cargar departamentos en los combobox
    private void cargarComboboxes() {
        Departamento[] deptos = controlador.obtenerDepartamentosActuales();

        // Limpiar comboboxes
        departamentoOrigen.removeAllItems();
        departamentoDestino.removeAllItems();

        // Llenar comboboxes
        for (Departamento depto : deptos) {
            departamentoOrigen.addItem(depto.getId() + " - " + depto.getNombre());
            departamentoDestino.addItem(depto.getId() + " - " + depto.getNombre());
        }
    }
    
    // Metodo encargado de trasladar articulos
    private void trasladarArticulos() {
        try {
            // Extraer IDs de los comboboxes
            String origenStr = (String) departamentoOrigen.getSelectedItem();
            String destinoStr = (String) departamentoDestino.getSelectedItem();

            // Ref: https://es.stackoverflow.com/questions/45846/c%C3%B3mo-separar-un-string-en-java-c%C3%B3mo-utilizar-split
            int idOrigen = Integer.parseInt(origenStr.split(" - ")[0]);
            int idDestino = Integer.parseInt(destinoStr.split(" - ")[0]);

            // Trasladar
            controlador.trasladarArticulos(idOrigen, idDestino);

            // Actualizar tabla
            cargarDepartamentosEnTabla();
            cargarComboboxes();
        } catch (IllegalStateException e) {
            // Error de Operacion - mensaje específico
            JOptionPane.showMessageDialog(this, 
                e.getMessage(), 
                "Error de Operacion", 
                JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
             // Error inesperado
             JOptionPane.showMessageDialog(this, 
                 "Error inesperado: " + e.getMessage(), 
                 "Error", 
                 JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void departamentoOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departamentoOrigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_departamentoOrigenActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonTrasladarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTrasladarActionPerformed
        trasladarArticulos();
    }//GEN-LAST:event_botonTrasladarActionPerformed

    private void botonRefrescarDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRefrescarDepartamentosActionPerformed
        cargarDepartamentosEnTabla();
        cargarComboboxes();
    }//GEN-LAST:event_botonRefrescarDepartamentosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonRefrescarDepartamentos;
    private javax.swing.JButton botonTrasladar;
    private javax.swing.JScrollPane contenedorTabla;
    private javax.swing.JComboBox<String> departamentoDestino;
    private javax.swing.JComboBox<String> departamentoOrigen;
    private javax.swing.JLabel lbOrigen;
    private javax.swing.JLabel lblDestino;
    private javax.swing.JTable tablaContenido;
    private javax.swing.JLabel tituloTablaDepartamento;
    private javax.swing.JLabel tituloVentana;
    // End of variables declaration//GEN-END:variables
}
